name: terraform-tutorials-ci

on: [push, pull_request]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true  

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Terraform
        uses: marocchino/setup-terraform@v1
        with:
          version: "0.12.15"
      - name: Build module 'aws-instance-first-script'
        run: cd aws-instance-first-script && terraform init && terraform validate && terraform plan 
      - name: Build module 'aws-EC2-with-jenkins'
        run: cd EC2withJenkins && terraform init && terraform validate && terraform plan
      - name: Build module 'aws-Application-Load-Balancer'
        run: cd terraform-aws-elb-alb && terraform init && terraform validate && terraform plan
